### ISSUE TITLE
Plugin install directory and muplugins_loaded()

### ISSUE THREAD

**Issue by elvismdev** [inpsyde/elastic-facets#2]
Does this plugin is meant to be run from `wp-content/plugins` or, `wp-content/mu-plugins` folder?

I'm curious about, because hooking into [muplugins_loaded()](https://github.com/inpsyde/elastic-facets/blob/master/elastic-facets.php#L19) doesn't run when located on `wp-content/plugins`, but in `wp-content/mu-plugins` does. However installing it via composer drops it into `wp-content/plugins`.

**Comment by dnaber-de** [comment]
Actually it's a library. The reason it is named as _plugin_ is that it can run some bootstrap code. 

However, the `mu-plugin` event is triggered for mu-plugins and network wide active plugins. On single site scope that won't work, that's correct. I'll fix this.
