### ISSUE TITLE
Filter search results by category facet

### ISSUE THREAD

**Issue by elvismdev** [inpsyde/elastic-facets#3]
Hi @dnaber-de,

I'm trying to filter down my search results by a selected category. However when I select this one and submit my category facet filter form still I'm getting returned all results, instead of the single post which have this category selected (aka the post with title "Hello Seattle").

![selection_026](https://cloud.githubusercontent.com/assets/3847077/26037682/7aba8968-38ad-11e7-9d08-cace32cd35c7.jpg)

I'm under the impression I'm still missing to transform the default ES query into a filtered query by category term. But, can't find to elaborate this the right way needed on `ep_formatted_args` while following the example mentioned in the [README here](https://github.com/inpsyde/elastic-facets/blob/master/README.md#elasticsearch-aggregations). Also I have noted by [this article here](https://www.elastic.co/blog/better-query-execution-coming-elasticsearch-2-0) that the usage of `filtered` is deprecated from Elasticsearch 2.0+.

I'm using Elasticsearch 2.4.5.

Could you give me some guidance how have you accomplished to filter search results like this?

Pretty much appreciated.

**Comment by dnaber-de** [comment]
How do you map your query string to main `WP_Query` object?

**Comment by elvismdev** [comment]
@dnaber-de I got this sorted out by filtering into [`ep_formatted_args_query`](https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-api.php#L1395) and having a [bool query](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/query-dsl-bool-query.html) with a `filter` clause. Was just that the example in the [readme](https://github.com/inpsyde/elastic-facets/blob/master/README.md#elasticsearch-aggregations) to narrow down the results wasn't working for me since the usage of `filtered` is deprecated in my current Elasticsearch instance which is v2.4.5.

Thank you!
```
add_filter(
    'ep_formatted_args_query',
    function( array $query, array $args ) {

       $category = get_query_var( 'category' );

		if ( $category ) 
			$query['bool']['filter'] = array(
				'term' => array(
					'terms.category.slug' => $category
					)
				);

		return $query;
    },
    20,
    2
}
```

**Comment by dnaber-de** [comment]
Why don't you use `WP_Query` instead by adding a tax query and let Elasticpress do the work for you?

**Comment by elvismdev** [comment]
I've changed my code to map the query string in `WP_Query` arguments like this and leverage Elasticpress do this work:

```
add_action(
    'pre_get_posts',
    function( $query ) {

                $category = get_query_var( 'category' );

		if ( $category ) {
			// Tax Query
			$tax_query = array(
				array(
					'taxonomy' => 'category',
					'field'    => 'slug',
					'terms'    => array( $category )
					)
				);
			$query->set( 'tax_query', $tax_query );
		}
      
    }
);
```

It does filters down my search results items obviously, so that part is good, but when using the example in the [readme](https://github.com/inpsyde/elastic-facets/blob/master/README.md) to add aggregations, it does not calculate them properly from my filtered query results, it returns me all category terms when I get them with `elastic_facets.get_registry` on the template, instead of giving me only one term since I have in my search results only 1 post that has this single taxonomy/category attached to it.

However following another approach, when I add aggregations manually [the way ElasticPress want it](https://github.com/10up/ElasticPress/blob/develop/classes/class-ep-api.php#L1518-L1540), they do work as I expect. 

Having the code on my `pre_get_posts` looking like this:
```
add_action(
    'pre_get_posts',
    function( $query ) {

                $category = get_query_var( 'category' );
		if ( $category ) {
			// Tax Query
			$tax_query = array(
				array(
					'taxonomy' => 'category',
					'field'    => 'slug',
					'terms'    => array( $category )
					)
				);
			$query->set( 'tax_query', $tax_query );
		}

                // Add Aggregations
		$aggs = array(
			'name' => 'the_facets',
			'use-filter' => true,
			'aggs' => array(
				'category' => array( 
					'terms' => array(
						'size' => 100, 
						'field' => 'terms.category.slug' 
						) 
					),
				'post_tag' => array( 
					'terms' => array(
						'size' => 100, 
						'field' => 'terms.post_tag.slug' 
						) 
					),
				),
			);

		$query->set( 'aggs', $aggs );
      
    }
);
```

So at this point I'm little confused, between if I'm missing something else to build this up using `elastic-facets` library API, or if there's probably something different to my Elasticsearch v2.4.5, mainly on the way to do queries and add aggregations.

What's your thoughts on this?
