### ISSUE TITLE
Could this be made into a WP plugin with a GUI?

### ISSUE THREAD

**Issue by MediaMaquina** [inpsyde/elastic-facets#4]
This seems exactly like i need. Use my existing ES server to filter posts but i can't code so i was wondering if a WP plugin could be made out of this? I would buy it. Just saying ;)

**Comment by bueltge** [comment]
Also see https://github.com/inpsyde/elastic-facets/issues/2#issuecomment-302686980

Currently we haven't approach or depend for a gui. So feel free to enhance the solution.
